# Azure pipeline used to trigger builds of the JPO Conflict Monitor project
# This pipeline is primarily used for CI in the CDOT-CV fork

trigger:
  branches:
    include:
      - develop
  paths:
    include:
      - 'jpo-conflictmonitor/*'

pool:
  vmImage: ubuntu-latest

steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        **
        !**/docs/**
        !**/*.md
        !**/test-message-sender
        !**/jpo-utils
        !**/samples
        !**/.github
        !**/.vscode
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  # Publish the artifacts directory for consumption in publish pipeline
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'jpo-conflictmonitor'
      publishLocation: 'Container'
