name: Docker Build

on:
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  jpo-conflictmonitor:
    uses: usdot-jpo-ode/actions/.github/workflows/docker.yml@main
    with:
      context: .
      file: Dockerfile
      build-args: |
        MAVEN_GITHUB_TOKEN_NAME=${{ vars.MAVEN_GITHUB_TOKEN_NAME }}
        MAVEN_GITHUB_ORG=${{ github.repository_owner }}
    secrets:
      MAVEN_GITHUB_TOKEN: ${{ secrets.MAVEN_GITHUB_TOKEN }}