name: DockerHub Build and Push

on:
  push:
    branches:
      - "develop"
      - "master"
      - "release/*"
    tags:
      - "*"
  workflow_dispatch:

jobs:
  dockerhub-jpo-conflictmonitor:
    uses: usdot-jpo-ode/actions/.github/workflows/dockerhub.yml@main
    with:
      image: usdotjpoode/geojsonconverter
      context: .
      file: Dockerfile
      build-args: |
        MAVEN_GITHUB_TOKEN_NAME=${{ vars.MAVEN_GITHUB_TOKEN_NAME }}
        MAVEN_GITHUB_ORG=${{ github.repository_owner }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN:   ${{ secrets.DOCKERHUB_TOKEN }}
      MAVEN_GITHUB_TOKEN: ${{ secrets.MAVEN_GITHUB_TOKEN }}
